/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionDashboardRouteImport } from './routes/reception.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionDashboardRoute = ReceptionDashboardRouteImport.update({
  id: '/reception/dashboard',
  path: '/reception/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reception/dashboard': typeof ReceptionDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reception/dashboard': typeof ReceptionDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reception/dashboard': typeof ReceptionDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reception/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reception/dashboard'
  id: '__root__' | '/' | '/reception/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceptionDashboardRoute: typeof ReceptionDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/dashboard': {
      id: '/reception/dashboard'
      path: '/reception/dashboard'
      fullPath: '/reception/dashboard'
      preLoaderRoute: typeof ReceptionDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceptionDashboardRoute: ReceptionDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
