// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const { data, error } = await supabase.auth.getSession()
      
      // If there's an error getting the session (like invalid refresh token),
      // we should clear local storage and force login to avoid infinite loops
      if (error) {
        console.error('[AUTH_ATTACH_ERROR] Session invalid:', error.message)
        if (typeof window !== 'undefined') {
          Object.keys(localStorage)
            .filter((k) => k.startsWith('sb-') || k.includes('supabase'))
            .forEach((k) => localStorage.removeItem(k));
          sessionStorage.clear();
          
          if (window.location.pathname !== '/login') {
            window.location.href = '/login'
          }
        }
        return next({ headers: {} })
      }

      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch (e) {
      return next({ headers: {} })
    }
  },
)
