// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phbrnbrdnxxwnhifsxvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoYnJuYnJkbnh4d25oaWZzeHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NjI3ODYsImV4cCI6MjA5MzMzODc4Nn0.FznVHCVLfh5ssnKBpCZxuGAi52SOha_cbGjoZ-hCxRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});